### ISSUE TITLE
Backend von TVStreamRecord läuft nicht mehr

### ISSUE THREAD

**Issue by todrees1967** [Pavion/tvstreamrecord#50]
Hallo und frohe Weihnachten, ich habe das Problem, dass das Backend von TVStreamRecord sich nicht mehr aufrufen lässt. Auf dem Port 8030 ist kein Dienst mehr aktiv, deshalb bekommen ich eine Fehlermeldung im Browser. Aufzeichnen scheint aber noch zu funktionieren, da eine tägliche Aufnahme nach wie vor gemacht wird. Das Logfile zeigt folgendes:

(Starting server on: 192.168.111.2:8030 ist richtig)..

Hat jemand eine Idee, woran das Problem liegt?

2020-12-25 17:00:13 OUT Using Python (python3)...
2020-12-25 17:00:15.294 Starting tvstreamrecord v.1.4.3c with Python 3.8
2020-12-25 17:00:15.295 Logging output initialized
2020-12-25 17:00:15.348 Initializing database...
2020-12-25 17:00:27.073 Initializing config...
2020-12-25 17:00:27.113 Checking internationalization...
2020-12-25 17:00:27.194 Initializing records...
2020-12-25 17:00:27.221 Initializing EPG import thread...
2020-12-25 17:00:27.226 Record: Thread timer for 'RTL Aktuell' started for 5972 seconds
2020-12-25 17:00:27.227 EPG Thread timer waiting till 01:00 (28772 seconds)
2020-12-25 17:00:27.228 Starting server on: 192.168.111.2:8030
2020-12-25 17:00:27.415 Server exception. Default network settings will be used this time. Please log in using port 8030 and check your network settings.
2020-12-25 17:00:27.415 Starting server on: 0.0.0.0:8030
2020-12-25 17:00:27.425 Traceback (most recent call last):
2020-12-25 17:00:27.425 File "tvstreamrecord.py", line 1347, in <module>
2020-12-25 17:00:27.431 run(host=config.cfg_server_bind_address, port=config.cfg_server_port, server=CherryPyServer, quiet=True)
2020-12-25 17:00:27.431 File "/volume1/@appstore/tvstreamrecord/bottle.py", line 3476, in run
2020-12-25 17:00:27.487 server.run(app)
2020-12-25 17:00:27.488 File "/volume1/@appstore/tvstreamrecord/bottle.py", line 3057, in run
2020-12-25 17:00:27.497 from cherrypy import wsgiserver
2020-12-25 17:00:27.497 File "/volume1/@appstore/tvstreamrecord/cherrypy/__init__.py", line 64, in <module>
2020-12-25 17:00:27.505 from cherrypy._cperror import HTTPError, HTTPRedirect, InternalRedirect
2020-12-25 17:00:27.505 File "/volume1/@appstore/tvstreamrecord/cherrypy/_cperror.py", line 118, in <module>
2020-12-25 17:00:27.508 from cgi import escape as _escape
2020-12-25 17:00:27.509 ImportError
2020-12-25 17:00:27.509 :
2020-12-25 17:00:27.509 cannot import name 'escape' from 'cgi' (/var/packages/py3k/target/usr/local/lib/python3.8/cgi.py)
2020-12-25 17:00:27.509 During handling of the above exception, another exception occurred:
2020-12-25 17:00:27.509 Traceback (most recent call last):
2020-12-25 17:00:27.509 File "tvstreamrecord.py", line 1351, in <module>
2020-12-25 17:00:27.515 run(host="0.0.0.0", port=8030, server=CherryPyServer, quiet=True)
2020-12-25 17:00:27.515 File "/volume1/@appstore/tvstreamrecord/bottle.py", line 3476, in run
2020-12-25 17:00:27.526 server.run(app)
2020-12-25 17:00:27.527 File "/volume1/@appstore/tvstreamrecord/bottle.py", line 3057, in run
2020-12-25 17:00:27.536 from cherrypy import wsgiserver
2020-12-25 17:00:27.536 File "/volume1/@appstore/tvstreamrecord/cherrypy/__init__.py", line 64, in <module>
2020-12-25 17:00:27.537 from cherrypy._cperror import HTTPError, HTTPRedirect, InternalRedirect
2020-12-25 17:00:27.538 File "/volume1/@appstore/tvstreamrecord/cherrypy/_cperror.py", line 118, in <module>
2020-12-25 17:00:27.539 from cgi import escape as _escape
2020-12-25 17:00:27.539 ImportError
2020-12-25 17:00:27.540 :
2020-12-25 17:00:27.540 cannot import name 'escape' from 'cgi' (/var/packages/py3k/target/usr/local/lib/python3.8/cgi.py)

Viele Grüße

Torsten

**Comment by Pavion** [comment]
Hi Torsten, 

das Problem sollte mit der neuen Version nicht vorkommen:
https://github.com/Pavion/tvstreamrecord/releases
Falls Du bereits Docker verwendest, kannst Du gern die Docker-Version ausprobieren, sie hat alle notwendigen Bibliotheken dabei und wird ab DSM7 u.U. die präferierte Lösung
https://github.com/Pavion/tvstreamrecord#docker

Gruß
Pav

**Comment by todrees1967** [comment]
Hi Pav, danke, aber Docker geht auf meiner DS nicht. Ich lade die neue Version mal runter, und teste diese.
Gruß
Torsten

**Comment by todrees1967** [comment]
Hi Pav, nach dem Update auf die neue Version lässt sich das Frontend wieder aufrufen. Vielen Dank für den prompten Support.
Gruß
Torsten
