### ISSUE TITLE
Cannot set a password

### ISSUE THREAD

**Issue by robaca** [Pavion/tvstreamrecord#52]
When I try to set a remote access password via the configuration, nothing happens on submit (dialog stays open).

I get the following error in the logs:

Traceback (most recent call last): File "/usr/lib/python3.8/site-packages/bottle.py", line 868, in _handle return route.call(**args) File "/usr/lib/python3.8/site-packages/bottle.py", line 1748, in wrapper rv = callback(*a, **ka) File "tvstreamrecord.py", line 164, in setPass pass_new_1 = hashlib.sha224(request.forms.pass_new_1).hexdigest() if request.forms.pass_new_1 else ""TypeError: Unicode-objects must be encoded before hashing

I'm using the latest docker image and the password contains no special characters.

**Comment by Pavion** [comment]
Fixed with https://github.com/Pavion/tvstreamrecord/commit/0696ba8b99833cc6daf3ee98480c58e4d3a84247, Docker build updated. Thanks for reporting this issue.
